export enum ProjectEnum {
  VERSION_2 = 'v2',
  VERSION_3 = 'v3',
  VERSION_4 = 'v4',

  PROJECT_LIST = 'PROJECT_LIST',
  PROJECT_VAR_DEFAULT = 'PROJECT_VAR_DEFAULT',
  PROJECT_VAR_CONFIG = 'PROJECT_VAR_CONFIG'
}
