export enum ThemeEnum {
  VERSION_2 = 'v2',
  VERSION_3 = 'v3',
  VERSION_4 = 'v4',

  APP_THEME_LIST = 'APP_THEME_LIST',
  APP_THEME_VAR_BASE = 'APP_THEME_VAR_BASE',
  APP_THEME_VAR_CONFIG = 'APP_THEME_VAR_CONFIG'
}
