export { default as APP_SETTING } from './setting'
export { APP_MENU_LIST } from './menu'
export { APP_STYLE_LIST, DEFAULT_COLOR } from './style'

export const APP_THEME_USER_CONFIG = 'APP_THEME_USER_CONFIG'
export const APP_THEME_PREVIEW_CONFIG = 'APP_THEME_PREVIEW_CONFIG'
export const APP_THEME_PREVIEW_ID = 'APP_THEME_PREVIEW_ID'

export const MESSAGE_INIT_STYLES = 'MESSAGE_INIT_STYLES'
export const MESSAGE_SET_STYLES = 'MESSAGE_SET_STYLES'
export const MESSAGE_CLEAR_STYLES = 'MESSAGE_CLEAR_STYLES'
export const MESSAGE_VANT_REPLACEPATH = 'replacePath'
