export const APP_THEME_USER_CONFIG = 'APP_THEME_USER_CONFIG'
export const APP_THEME_PREVIEW_CONFIG = 'APP_THEME_PREVIEW_CONFIG'
export const APP_OLD_PREVIEW_CONFIG = 'APP_OLD_PREVIEW_CONFIG'
export const APP_THEME_PREVIEW_ID = 'APP_THEME_PREVIEW_ID'
